/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_doraemon_wish_pack_AesJni */

#ifndef _Included_com_doraemon_wish_pack_AesJni
#define _Included_com_doraemon_wish_pack_AesJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_doraemon_wish_pack_AesJni
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_doraemon_wish_pack_AesJni_encrypt(JNIEnv *jniEnv, jobject thiz, jstring plaintext);

#ifdef __cplusplus
}
#endif
#endif
