spring:
  # 配置默认开发环境
  profiles:
    active: dev

  # redis配置

  #JPA 相关配置
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        # 显示SQL语句
    show-sql: true

  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 4096MB
      max-request-size: 4096MB

server:
  servlet:
    context-path: /doraemon/
  tomcat:
    uri-encoding: UTF-8
    accesslog:
      encoding: UTF-8

jwt:
  secret-key: C*F-JaNdRgUkXn2r5u8x/A?D(G+KbPeShVmYq3s6v9y$B&E)H@McQfTjWnZr4u7w
  expiration-time: 60 * 60 * 24 * 7L

