spring:

  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/doraemon?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 静态资源配置
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: "classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,\
    file:/Users/lbx/Music/word/,file:/Users/lbx/dev/temp/doraemon/plugin,\
    file:/Volumes/extend/doraemon/build-apk"

## 日志配置
#logging:
#  file: ./log/rest.log
#  level:
#    web: DEBUG

study-en:
  voice: /Users/lbx/Music/word/

pack:
  plugin-path: /Volumes/extend/doraemon/plugin
  apk-path: /Volumes/extend/doraemon/apk
  build-path: /Volumes/extend/doraemon/build
  build-apk-path: /Volumes/extend/doraemon/build-apk