spring:

  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/doraemon?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver

## 日志配置
#logging:
#  file: ./log/rest.log
#  level:
#    web: DEBUG

study-en:
  voice: /Users/lbx/Music/word/